update flightgear to 2020.3.8
flathub/org.flightgear.FlightGear pull request #32
Opened 2021-03-29 03:17 UTC by violetmage

2021-03-29 05:12 UTC, violetmage commented
404 >.<

`url-not-found         : <screenshot> failed to download (HTTP 404: Not Found) [http://wiki.flightgear.org/images/3/37/SOTY-2017.jpeg]`

2021-03-29 07:44 UTC, Vanadiae commented
I'll have a look later today, or during the week if I can't manage today.

2021-04-03 11:27 UTC, Vanadiae commented
> 404 >.<
> 
> `url-not-found : <screenshot> failed to download (HTTP 404: Not Found) [http://wiki.flightgear.org/images/3/37/SOTY-2017.jpeg]`

Yeah, just drop this screenshot for now. I'll add a bunch of nice screenshots from https://wiki.flightgear.org/Category:Screenshot_of_the_month in an other PR.

2021-04-03 11:42 UTC, Vanadiae requested changes
Once the 404 error'ed screenshot is removed and a new build is available, I'll test flightgear then merge it if everything's fine.

2021-04-03 11:42 UTC, Vanadiae commented on org.flightgear.FlightGear.yaml
> +    sha1: 8f919b22422c8ba708bba22c638416b9878031cc
Please prefer using a sha256 as sha1 is unsafe. You can firs try replacing this line with `sha256: some_foobar_garbage` and the build will give you the correct sha256 saying something like `Expected sha256 some_foobar_garbage but got c11a6c6dd596a82dd9bf59326c2ef7fb971ba79a236b4036db633bb6721a41ff` so here you'll just need to copy paste the sha256 it showed.

2021-04-04 17:42 UTC, Vanadiae commented
So I played a bit and I didn't notice any problem, so I'm merging :) Thanks again for updating flightgear! I noticed that sourceforge provides RSS feeds for releases files, so I'm adding it to my feed reader so hopefully next time I'll notice there's an update available and so, update the flatpak here :)

2021-04-04 17:47 UTC, merged

2021-04-04 17:48 UTC, Vanadiae commented
BTW your git commit email is not set correctly. It seems like it's your computer's hostname instead?

2021-04-04 19:17 UTC, violetmage commented
ah, is true

many thanks for information :)